# Generated by Django 5.2.6 on 2026-01-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax_date',
            new_name='tax_data',
        ),
    ]
